[package]
name = "stress-cpu"
version = "0.2.0"
edition = "2021"
description = "Utility that simulates a high cpu load."
license = "MIT OR Apache-2.0"

[dependencies]
num_cpus = "1.16.0"
rand = "0.8.5"
tokio = { version = "1.41.1", features = ["full"] }
